name = "weixin-webhook-worker"
main = "src/index.js"
compatibility_date = "2026-09-20"
workers_dev = true

[[kv_namespaces]]
binding = "WEIXIN_KV"

[vars]
WEIXIN_CHANNEL_VERSION = "2.4.9"
WEIXIN_APP_ID = "bot"
